version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo Installing dependencies...”
          npm install
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm ci
      - snyk/install
      - run:
          command: snyk version
          name: Which version of snyk is installed
      - run:
          command: snyk code test
          name: Run code scan
          
jobs:
    scan:
        docker:
            - image: cimg/node:16.10
        steps:
            - checkout
            - setup_remote_docker      
            - docker/check
            - docker/build:
                image: nbtai7777/education-space
            - snyk/scan: 
                docker-image-name: nbtai7777/education-space

workflows:
  simple_workflow:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - test:
          requires:
            - build 
          filters:
            branches:
              only: main    

    # The scan job
      - scan:
          requires:
            - build
          filters:
            branches:
              only: main
    # The scan job
      - scan:
        requires:
          -build
          filters:
            branches:
              only: main     
